### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [python/typed_ast#100]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by gvanrossum** [comment]
There's no `sudo: false` in this project's `.travis.yml`. There are two occurrences of `sudo: required` but those don't seem to be covered by the Travis blog post you mention, so I'm closing this.

**Comment by webknjaz** [comment]
Any `sudo:` instance can be removed as it doesn't influence anything anymore. Prior to that change, it'd explicitly instruct Travis CI to use a docker container or a VM. Now they only do VMs unconditionally.

**Comment by cclauss** [comment]
Yes.  This was discussed at python/mypy#6675

**Comment by gvanrossum** [comment]
OK, send a PR. :-)
