### ISSUE TITLE
missing wheels for windows

### ISSUE THREAD

**Issue by danielhrisca** [python/typed_ast#102]
There are no Windows wheels for release 1.3.4 on PyPi 

![image](https://user-images.githubusercontent.com/20952040/56356212-d96eda00-61e0-11e9-8bc1-fd685507cd20.png)

**Comment by CfirTsabari** [comment]
hi,
I think this might be related to typed-ast now require visual c++14 on windows.

here an output of my jenkins trying to install typed-ast


`
Building wheels for collected packages: typed-ast
  Building wheel for typed-ast (setup.py): started
  Building wheel for typed-ast (setup.py): finished with status 'error'
  Complete output from command "python.EXE" -u -c "import setuptools, tokenize;__file__='setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d 
pip-wheel-z76dhbcr --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\typed_ast
  copying typed_ast\ast27.py -> build\lib.win32-3.7\typed_ast
  copying typed_ast\ast3.py -> build\lib.win32-3.7\typed_ast
  copying typed_ast\conversions.py -> build\lib.win32-3.7\typed_ast
  copying typed_ast\__init__.py -> build\lib.win32-3.7\typed_ast
  package init file 'ast3\tests\__init__.py' not found (or not a regular file)
  creating build\lib.win32-3.7\typed_ast\tests
  copying ast3\tests\test_basics.py -> build\lib.win32-3.7\typed_ast\tests
  running build_ext
  building '_ast27' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  
  ----------------------------------------
  Failed building wheel for typed-ast
  Running setup.py clean for typed-ast
Failed to build typed-ast
`

**Comment by danielhrisca** [comment]
@CfirTsabari 

this is what triggered me as well

**Comment by CfirTsabari** [comment]
that issues doesn't seem related to a problem on AppVeyor because you can download the wheels from this [link ](https://ci.appveyor.com/project/ddfisher/typed-ast-a4xqu/builds/23935378)

**Comment by msullivan** [comment]
Oops. Fixed!
