### ISSUE TITLE
"py36" AST needed

### ISSUE THREAD

**Issue by ambv** [python/typed_ast#106]
I think because of async and await handling, typed_ast needs to grow a third AST option: `py36` for handling Python 3.0 - 3.6.

Rationale:
- we need async and await as pseudo-keywords for handling 3.0 - 3.6 code with annotations and "async" and/or "await" names;
- with LL(1) we need async and await as keywords for handling all 3.7+ cases of async generators and parens-less await expressions.

This should be easy to accomplish and maintain, "py3" requires no changes, "py36" would be what you had before merging changes from Python 3.7.

Is there a different way in which the same compatibility is accomplished by, say, mypy?

**Comment by gvanrossum** [comment]
Mypy uses a flag named ‘feature_version’.

**Comment by ambv** [comment]
That works, sorry for the noise.
