### ISSUE TITLE
add typed_ast server

### ISSUE THREAD

**Issue by jgirardet** [python/typed_ast#107]
Hi,
I have to use old python version but parse ast of newer python version.
I was thinking to create a simple http server (ala blackd) under latest python version which would  deal with ast and return tree/node.
This should be a binary (for example using pyinstaller) to make it run without the latest python version installed.
before I start it in my own, would you be interested to add it to typed_ast ?

**Comment by gvanrossum** [comment]
I'm not interested in this -- the use case appears very niche and we're trying to wind down support for typed_ast over the next several years. You should easily be able to create your own GitHub project for this purpose though. Good luck!

**Comment by mbdevpl** [comment]
@jgirardet If you're considering this, then please notice that typed_ast was merged into CPython, and will appear in 3.8 https://docs.python.org/dev/library/ast.html#ast.parse - and therefore the server could just need to run core Python 3.8. But then the problem would be to transform/downgrade the tree from latest Python to the older one...
