### ISSUE TITLE
Version 1.4.0 requires Microsoft Windows SDK 7.1

### ISSUE THREAD

**Issue by jgsogo** [python/typed_ast#122]
Hi, we recently found in our CI that in order to install `typed-ast` for python 3.4 in Windows we need a newer Microsoft Windows SDK (v 7.1). Is it intentional? Can it be reverted? Our main issue is not with our CI, sure we can install the new SDK, but with our users that can find the same error when installing our product.

Full log [output](https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanNightly/detail/ConanNightly/518/pipeline):

```
  Running setup.py install for typed-ast: started
    Running setup.py install for typed-ast: finished with status 'error'
    ERROR: Complete output from command 'd:\j\t\9f6d\py34\disabled_revisions\venv\scripts\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Jenkins\\AppData\\Local\\Temp\\2\\pip-install-2jlu6nis\\typed-ast\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Jenkins\AppData\Local\Temp\2\pip-record-r0fif5f_\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\j\t\9f6d\py34\disabled_revisions\venv\include\site\python3.4\typed-ast':
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.4
    creating build\lib.win32-3.4\typed_ast
    copying typed_ast\ast27.py -> build\lib.win32-3.4\typed_ast
    copying typed_ast\ast3.py -> build\lib.win32-3.4\typed_ast
    copying typed_ast\conversions.py -> build\lib.win32-3.4\typed_ast
    copying typed_ast\__init__.py -> build\lib.win32-3.4\typed_ast
    package init file 'ast3\tests\__init__.py' not found (or not a regular file)
    creating build\lib.win32-3.4\typed_ast\tests
    copying ast3\tests\test_basics.py -> build\lib.win32-3.4\typed_ast\tests
    running build_ext
    building '_ast27' extension
    error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1": www.microsoft.com/download/details.aspx?id=8279
```

As this is a transitive dependency of `astroid` lib I'm writing to them too.

Thanks!

**Comment by ilevkivskyi** [comment]
Python 3.4 reached its EoL few months ago and not a supported version anymore.

**Comment by jgsogo** [comment]
Ok, thanks.

Having a look to the file `typed_ast/build.cmd` file I can see that the Microsoft SDK 7.1 has been there for various releases, so the problem is that you no longer create compiled versions for python 3.4, right?

We'll try to get rid of that python version too, thanks for pointing EoL out

**Comment by ilevkivskyi** [comment]
> so the problem is that you no longer create compiled versions for python 3.4, right?

Yes.

**Comment by gvanrossum** [comment]
Presumably if you pinned the typed_ast version to 1.3.5 it would work?

**Comment by jgsogo** [comment]
Yes @gvanrossum , the problem we have is that `typed-ast` is a transitive dependency of `astroid`, so we need them to freeze it (right now they have `>1.3.0` [here](https://github.com/PyCQA/astroid/blob/01a25f31962dd5017a141a6450859a7c1c82722d/astroid/__pkginfo__.py#L33)).... or add it as a dependency of our project (with the same conditioning as the do). Right now we are waiting for[ their answer](https://github.com/PyCQA/astroid/issues/676) and we will decide in a couple of days.

Thanks!

**Comment by gvanrossum** [comment]
I guess I missed what project you are working on?
-- 
--Guido (mobile)

**Comment by jgsogo** [comment]
I'm part of the Conan team, an open source package manager for C/C++: https://github.com/conan-io

**Comment by gvanrossum** [comment]
Oh cool!
