### ISSUE TITLE
It's probably time for a release

### ISSUE THREAD

**Issue by gvanrossum** [python/typed_ast#129]
Python 3.9a1 just came out and `pip3 install typed_ast` fails. It's fixed by #128.

**Comment by JukkaL** [comment]
Sounds good -- I wonder who knows how to do a typed_ast release?

**Comment by msullivan** [comment]
The release process is documented at
https://github.com/python/typed_ast/blob/master/release_process.md

**Comment by JukkaL** [comment]
I can give it a try (probably this week or the next).

**Comment by tk0miya** [comment]
Is there any plan for release?
It seems Travis CI started to use 3.9.0a2+ for its "nightly" platform (maybe since yesterday). So it is helpful to us if you released new version.

**Comment by gvanrossum** [comment]
If nobody has time I can take care of this in the next few days.

**Comment by gvanrossum** [comment]
Done

**Comment by tk0miya** [comment]
Thanks a lot!
