### ISSUE TITLE
Linker error in debug build on Windows

### ISSUE THREAD

**Issue by danielmenzel** [python/typed_ast#130]
I tried building a debug version of typed-ast on Windows (Python 3.7.5, Visual Studio 2015):
```cmd
> cd D:\Repos\github.com\python\typed_ast
> c:\Python37\python_d.exe setup.py build --debug
```

I first get a warning about inconsistent DLL linkage
```cmd
D:\Repos\github.com\python\typed_ast\ast27\Parser\parser.c(18): warning C4273: 'Py_DebugFlag': inconsistent dll linkage
c:\python37\include\pydebug.h(10): note: see previous definition of 'Py_DebugFlag'
```

and then a linker error:
```cmd
Creating library build\temp.win-amd64-3.7-pydebug\Debug\ast27/Parser\_ast27_d.cp37-win_amd64.lib and object build\temp.win-amd64-3.7-pydebug\Debug\ast27/Parser\_ast27_d.cp37-win_amd64.exp
parser.obj : error LNK2001: unresolved external symbol Py_DebugFlag
build\lib.win-amd64-3.7-pydebug\typed_ast\_ast27_d.cp37-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\link.exe' failed with exit status 1120
```

(this also happens with Visual Studio 2019)

I was able to fix it by changing the line
```python
extern int Py_DebugFlag;
```

to
```python
PyAPI_DATA(int) Py_DebugFlag;
```

in `ast27/Parser/parser.c` and `ast3/Parser/parser.c`. However I am not sure if that is the correct approach as I have not a lot of knowledge about the CPython internals.

**Comment by JukkaL** [comment]
I'm just guessing, but maybe the variable should be renamed, if it's conflicting with a variable with the same name in CPython?

**Comment by gvanrossum** [comment]
I think @danielmenzel is right. This is a flag exported by the CPython API, and that needs the magic of that macro. See https://github.com/python/cpython/blob/dc0284ee8f7a270b6005467f26d8e5773d76e959/Include/pydebug.h#L10

@danielmenzel Can you prepare a PR?
