### ISSUE TITLE
typed_ast.ast27 raises SyntaxError on coding declarations

### ISSUE THREAD

**Issue by r3m0t** [python/typed_ast#133]
```
>>> typed_ast.ast27.parse(b'# coding: utf-8\nfoo=2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\python3.7\site-packages\typed_ast\ast27.py", line 50, in parse
    return _ast27.parse(source, filename, mode)
  File "<unknown>", line 0
SyntaxError: encoding declaration in Unicode string
```

**Comment by gvanrossum** [comment]
Confirmed, and also confirmed that the stdlib ast module doesn't have this problem (in Python 3.7, 3.8 and in Python 2.7). Ironically, passing it a Unicode string with an encoding declaration doesn't trigger this error.

(I wouldn't call it a crash though. It's reporting a SyntaxError.)

@r3m0t, do you feel up to trying to coming up with a fix?

**Comment by msullivan** [comment]
(I know mypy handles coding declarations itself and passes a str to
typed_ast. )

**Comment by r3m0t** [comment]
Yep, I'll send something along

**Comment by gvanrossum** [comment]
Ping? Does anyone else care?

**Comment by r3m0t** [comment]
My branch didn't work, I worked around it in my own code instead, so nobody cares any longer
