### ISSUE TITLE
Chokes on annotated unparenthesised tuples

### ISSUE THREAD

**Issue by retnikt** [python/typed_ast#136]
## How to reproduce
Call `typed_ast.ast3.parse("foo: tuple = 5,")`

## Expected behaviour
Return:
```
Module(
    body=[
        AnnAsign(
            target=Name(
                id="foo"
            ),
            simple=1,
            value=Tuple(
                elts=[
                    Constant(
                        n=5,
                        s=5,
                        kind=""
                    )
                ]
            ),
            annotation=Name(
                    id="tuple"
            )
        )
    ],
    type_ignores=[]
)
```
## Actual Behaviour
```
>>> typed_ast.ast3.parse("foo: tuple = 5,")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/typed_ast/ast3.py", line 62, in parse
    return _ast3._parse(source, filename, mode, feature_version)
  File "<unknown>", line 1
    foo: tuple = 5,
                  ^
SyntaxError: invalid syntax
```
This behaviour does not occur with normal stdlib `ast`, or when removing the annotation, or when removing the comma to make it a simple value, or when putting the tuple in parentheses.

**Comment by retnikt** [comment]
I just realised this used to be a syntax error before Python 3.8, if that is relevant.

**Comment by gvanrossum** [comment]
typed_ast does not support (all of) Python 3.8. To parse 3.8, you have to run Python 3.8 or higher and use the stdlib `ast.parse()` function.

**Comment by retnikt** [comment]
Are there any plans to support these Python 3.8 changes?

**Comment by gvanrossum** [comment]
Not in typed_ast. I looked into it and it would be an overwhelming amount of work to update typed_ast.
