### ISSUE TITLE
Error Installing Pybinsim on Windows with Python 3.8

### ISSUE THREAD

**Issue by hmza09** [python/typed_ast#140]
I encountered the following error while installing pybinsim using anaconda. I'm using Windows 10 and Python 3.8
`$ conda create --name binsim python=3.5 numpy
$ source activate binsim
$ pip install pybinsim`

It run into following error
>  ERROR: Command errored out with exit status 1:
   command: 'c:\python3.8\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ihmza\\AppData\\Local\\Temp\\pip-install-ub5pe6rl\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\ihmza\\AppData\\Local\\Temp\\pip-install-ub5pe6rl\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ihmza\AppData\Local\Temp\pip-wheel-_udtfpya'
       cwd: C:\Users\ihmza\AppData\Local\Temp\pip-install-ub5pe6rl\pyaudio\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  copying src\pyaudio.py -> build\lib.win32-3.8
  running build_ext
  building '_portaudio' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyaudio

The MS Visual C++ error was gone when I downloaded the VS Build Tools 2019 but it lead to another error along with the top error

> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

**Comment by gvanrossum** [comment]
Sorry, this is not the right tracker for your issue.
