### ISSUE TITLE
Wheel support for aarch64

### ISSUE THREAD

**Issue by odidev** [python/typed_ast#141]
**Summary**
Installing typed-ast on aarch64 via pip using command "pip3 install typed-ast" tries to build wheel from source code

**Problem description**
typed-ast don't have wheel for aarch64 on PyPI repository. So, while installing typed-ast via pip on aarch64, pip builds wheel for same resulting in it takes more time to install typed-ast. Making wheel available for aarch64 will benefit aarch64 users by minimizing typed-ast installation time.

**Expected Output**
Pip should be able to download typed-ast wheel from PyPI repository rather than building it from source code.

@typed-ast-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make typed-ast wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by ethanhs** [comment]
I'm not aware of a format like manylinux for aarch64 or ARM in general. AIUI there are separate repositories that have been set up for the likes of the raspberry pi?

**Comment by odidev** [comment]
@ethanhs, manylinux 2014 has given AArch64 support. Also, pypi is supporting AArch64 wheel as well. Please let me know if I can help you in this activity. 

Thanks

**Comment by odidev** [comment]
Ping @ethanhs, can you please look at above [comment](https://github.com/python/typed_ast/issues/141#issuecomment-652240918) and let me know your thoughts.

**Comment by ethanhs** [comment]
I didn't realize these changes had been made, that's really great. I don't see why we couldn't add an aarch64 build of typed_ast to CI, especially since an aarch64 manylinux docker container is provided. Would you like to make a PR?

**Comment by odidev** [comment]
Thanks for the quick response. Yes, I will work and will make a PR into it.

**Comment by odidev** [comment]
Ping @ethanhs,
I have raised a PR for adding arm64 jobs in travis CI. #142 
Please review and suggest if any changes are required.

Also,please  let me know about the next step.

Thanks

**Comment by odidev** [comment]
@msullivan 

Please let me know when can we expect the wheel for aarch64.

Thanks
