### ISSUE TITLE
typed_ast causes `IndentationError` when using "sphinx-autodoc-typehints" package

### ISSUE THREAD

**Issue by demitri** [python/typed_ast#143]
Details of issue are here: https://github.com/agronholm/sphinx-autodoc-typehints/issues/139

**Comment by gvanrossum** [comment]
Can you repro it outside Sphinx? Just a file that is parsed correctly by ast but causes this error when parsed with typed_ast. Show the full input (including what comes *before* the error.

**Comment by gvanrossum** [comment]
Closing, as this doesn't seem to be caused by anything in typed_ast.

See https://github.com/agronholm/sphinx-autodoc-typehints/issues/139#issuecomment-666513756 (and previous comments).
