### ISSUE TITLE
Who has owner permissions on this repo?

### ISSUE THREAD

**Issue by gvanrossum** [python/typed_ast#149]
I don't, even though I've been doing releases (I do have owner permissions for the PyPI project).

**Comment by msullivan** [comment]
Not me. Either @JukkaL or @ddfisher?

**Comment by ddfisher** [comment]
I thought surely the answer would be me, but I don't either.

**Comment by JukkaL** [comment]
Looks like I'm the only admin. Who wants admin access to increase the bus factor?

**Comment by gvanrossum** [comment]
I'm up for it; @msullivan too I hope?

**Comment by msullivan** [comment]
Sure.

**Comment by JukkaL** [comment]
@gvanrossum @msullivan You are both admins now.

**Comment by JelleZijlstra** [comment]
FYI, @srittau, @hauntsaninja and I now also have permissions on this repo.
