### ISSUE TITLE
Module load fails with Python 3.9.8 (undefined symbol _PyUnicode_DecodeUnicodeEscape)

### ISSUE THREAD

**Issue by rra** [python/typed_ast#169]
Attempting to import the module as installed from PyPI (x86_64 architecture) on Python 3.9.8 produces the following exception:

```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo8e93dzwn/py_env-python3/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/.cache/pre-commit/repo8e93dzwn/py_env-python3/lib/python3.9/site-packages/black/__init__.py", line 52, in <module>
    from typed_ast import ast3, ast27
  File "/home/runner/.cache/pre-commit/repo8e93dzwn/py_env-python3/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /home/runner/.cache/pre-commit/repo8e93dzwn/py_env-python3/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```

This appears to have broken between Python 3.9.7 and Python 3.9.8.

**Comment by rra** [comment]
For others who may find this in a search, I ran into this problem via black because I had black pinned to an older version. The current version of black appears to no longer use typed-ast and thus won't encounter this issue.

**Comment by hroncok** [comment]
```python
diff --git a/ast3/Python/ast.c b/ast3/Python/ast.c
index cfca73f..93da89c 100644
--- a/ast3/Python/ast.c
+++ b/ast3/Python/ast.c
@@ -56,6 +56,8 @@ _PyBytes_DecodeEscape(const char *s,
     return PyBytes_DecodeEscape(s, len, errors, unicode, recode_encoding);
 }
 
+#endif
+
 PyObject *
 _PyUnicode_DecodeUnicodeEscape(const char *s,
                                Py_ssize_t size,
@@ -66,7 +68,6 @@ _PyUnicode_DecodeUnicodeEscape(const char *s,
     return PyUnicode_DecodeUnicodeEscape(s, size, errors);
 }
 
-#endif
 
 static int validate_stmts(asdl_seq *);
 static int validate_exprs(asdl_seq *, expr_context_ty, int);
```

This seems to get the job done.

**Comment by anthrotype** [comment]
I actually encountered this problem not while running black, but while running pytype. So what's the fix? Is there one?

**Comment by rra** [comment]
It looks like both mypy and black previously used typed-ast and no longer do. black at least (I haven't checked mypy) has switched to using the `ast` module included in Python for Python 3.8 and later. I suspect that's also the correct fix for pytype given https://github.com/python/typed_ast/issues/170.

**Comment by zerocewl** [comment]
The last workaround is using `python@3.9.7`...

**Comment by hauntsaninja** [comment]
Thanks for reporting, @hroncok are you willing to make a PR?

**Comment by hroncok** [comment]
Here you go https://github.com/python/typed_ast/pull/171

**Comment by hauntsaninja** [comment]
Specifically, when running on Python 3.8 and later, black / mypy will only use typed-ast to check / format Python 2 code. Recent releases of black / mypy have made Python 2 support an "extra", so they no longer install typed-ast unless you do e.g. `pip install "mypy[python2]"`.

I'm not sure what exactly pytype's usage of typed-ast looks like, but I imagine it could do something similar. Later today I'll make a release with a fix (thanks to hroncok!), in which case the solution will be to install that newly released typed-ast.

**Comment by anthrotype** [comment]
Many thanks for the quick fix! I have no idea what exactly pytype does with typed_ast, hopefully they will be able to sort it out like black and mypy have.

**Comment by steve-mavens** [comment]
Thanks for the fix! Do you have an ETA on when a release with this change will hit pypi? I'm just deciding whether or not to move to the latest black. If you're going to release soon then I need not bother! :-)

**Comment by srittau** [comment]
I believe @hauntsaninja wanted to do a release. If they have other commitments, I will see whether I can do a release today.

**Comment by steve-mavens** [comment]
That's fantastic, thank you. I've migrated one repo to the latest black, but this means I can leave the rest alone, since I don't think we need to do any other 3.9 builds today.

**Comment by hauntsaninja** [comment]
Released typed-ast 1.5.0 which includes this fix

**Comment by FierceElements** [comment]
I'm running into this when doing a "poetry install" on an existing project that requires `sqlalchemy-stubs`.

> Specifically, when running on Python 3.8 and later, black / mypy will only use typed-ast to check / format Python 2 code. Recent releases of black / mypy have made Python 2 support an "extra", so they no longer install typed-ast on Python 3.8+ unless you do e.g. `pip install "mypy[python2]"`.

I'm not so sure that's the case. It looks like the latest version of mypy still depends on typed-ast and even restricts it to 1.4, meaning it won't pick up the fix in 1.5.

```
% poetry show --tree
[...]
sqlalchemy-stubs 0.3 SQLAlchemy stubs and mypy plugin
├── mypy >=0.720
│   ├── mypy-extensions >=0.4.3,<0.5.0 
│   ├── typed-ast >=1.4.0,<1.5.0 
│   └── typing-extensions >=3.7.4
[...]

% poetry show mypy            
name         : mypy
version      : 0.770
description  : Optional static typing for Python

dependencies
 - mypy-extensions >=0.4.3,<0.5.0
 - typed-ast >=1.4.0,<1.5.0
 - typing-extensions >=3.7.4

% poetry run python --version
Python 3.9.10
```

Any advice appreciated.

**Comment by JelleZijlstra** [comment]
mypy 0.770 is very old, the current version is 0.931. You should upgrade.

**Comment by FierceElements** [comment]
Thanks @JelleZijlstra. I falsely assumed Poetry was installing the latest mypy. I deleted my initial comment, since it's a distraction for those visiting this issue. Feel free to delete yours, and I'll remove this one, too.

**Comment by YingboFu** [comment]
Hi, I've just encountered that module load fails with Python 3.9.13 (undefined symbol _PyUnicode_DecodeUnicodeEscape). I guess it is the same cause with other issues reported in this thread.
