### ISSUE TITLE
Release 1.4.4

### ISSUE THREAD

**Issue by vfazio** [python/typed_ast#174]
Any chance a tag for 1.4.4 will be created and new wheels, including 3.10, will be published?

**Comment by hauntsaninja** [comment]
Yeah, I'm making a release today.

**Comment by hauntsaninja** [comment]
I tagged and released 1.5.0, includes Python 3.10 wheels

**Comment by srittau** [comment]
To fix the mypy compatibility problems, I believe we should do a 1.4.4  release as well that just backports the Python 3.9 fix.

**Comment by srittau** [comment]
On the other hand, considering the problems with wheel on 1.4, this might not be worth the hassle. Let's hope mypy 0.920 gets released soon.
