### ISSUE TITLE
any way of turning an AST instance back into Python source code?

### ISSUE THREAD

**Issue by graingert** [python/typed_ast#25]

**Comment by mbdevpl** [comment]
In other words, "unparsing".

For untyped, see https://pypi.python.org/pypi/astunparse
For typed, see https://pypi.python.org/pypi/typed-astunparse (I'm the author)

Note: neither supports Python 3.6 at the moment.

**Comment by graingert** [comment]
@mbdevpl ah nice, can you release an sdist?

**Comment by mbdevpl** [comment]
For the time being, source is available here: https://github.com/mbdevpl/typed-astunparse - but I can also release sdist if necessary.
