### ISSUE TITLE
No type comments on AsyncWith/AsyncFor?

### ISSUE THREAD

**Issue by afrieder** [python/typed_ast#27]
From Python.asdl in ast35:

`For(expr target, expr iter, stmt* body, stmt* orelse, string? type_comment)`
`With(withitem* items, stmt* body, string? type_comment)`
but
`AsyncFor(expr target, expr iter, stmt* body, stmt* orelse)`
`AsyncWith(withitem* items, stmt* body)`

I don't believe there's anything against using type comments in async withs/fors, and this limits how MyPy can analyze them.

**Comment by ddfisher** [comment]
Fixed as of 1.0.0!
