### ISSUE TITLE
Add ast36

### ISSUE THREAD

**Issue by telendt** [python/typed_ast#29]
I've just tried `mypy --fast-parser --python-version 3.6` on code that utilizes some new Python 3.6 features and it failed.

Breaking features:
* formatted string literals, [PEP 498](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) -- `error: invalid syntax`
* asynchronous generators, [PEP 525](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep525) -- `error: 'yield' in async function`
* asynchronous comprehensions, [PEP 530](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep530) -- `error: invalid syntax`

**Comment by ddfisher** [comment]
Thanks for the bug report.  I'm planning on working on full 3.6 support in the next week or two (and documenting how typed_ast will be updated for new Python releases).

**Comment by kirbyfan64** [comment]
F-string are in #22... *still*... ;)

**Comment by JelleZijlstra** [comment]
I don't think async generators and comprehensions need further work in typed_ast. I have a pending pull request to mypy (https://github.com/python/mypy/pull/2711) to add async generators, and it didn't require typed_ast changes. Async comprehensions work fine for me with the latest release of mypy.

**Comment by ddfisher** [comment]
Fixed as of 1.0.0!  Mypy support pending here: https://github.com/python/mypy/pull/2857.
