### ISSUE TITLE
switch to setuptools and provide wheels.

### ISSUE THREAD

**Issue by graingert** [python/typed_ast#3]

**Comment by ddfisher** [comment]
Would you mind elaborating a bit?  What's the benefit of switching to setuptools?

**Comment by graingert** [comment]
@ddfisher this lets you build OS X and Windows wheels using travis and appveyor. It also lets you build manylinux wheels.

**Comment by ddfisher** [comment]
Providing wheels (especially for Windows) is something I'd like to start doing soon.  I'll look into using Appveyor.

**Comment by ddfisher** [comment]
As of typed_ast 0.6.2 32-bit and 64-bit Windows wheels for Python 3.5 are now provided.  I uploaded an OS X wheel from my machine, but I'll look into using Travis to provide broader OS X support.

**Comment by graingert** [comment]
@ddfisher any chance of 3.6 wheels?

**Comment by graingert** [comment]
@ddfisher any chance of manylinx1 wheels?

**Comment by ddfisher** [comment]
That's something I'd like to provide (and have spent some time looking into), but have some higher priority things to do in the meantime.  See [this comment](https://github.com/python/mypy/pull/2452#issuecomment-271033058) for more info.

**Comment by ddfisher** [comment]
After a somewhat arduous process (mainly revolving around finding a reasonable place to upload the built wheels), b61b826de4a1deb6521985abc6a0fb5e5232bede adds support for building manylinux wheels. Unfortunately, I'm now having trouble getting PyPI to accept the wheels:
```
twine upload dist/typed_ast-1.0.0-cp33-cp33m-linux_x86_64.whl
[...]
HTTPError: 400 Client Error: Binary wheel 'typed_ast-1.0.0-cp33-cp33m-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'. for url: https://upload.pypi.org/legacy/
```

**Comment by ddfisher** [comment]
manylinux wheels now uploaded for typed_ast 1.0.0!
