### ISSUE TITLE
Segfault on f-string in ast3

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typed_ast#30]
This happens:
```
Python 3.5.1 |Anaconda custom (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

>>> from typed_ast import ast3
>>> ast3.parse("x = f'Hi {x}'")
Segmentation fault: 11
```
Unfortunately, I could not test this on other versions of Python now.

**Comment by ilevkivskyi** [comment]
I discovered it fails even on correct f-strings:
```
>>> ast3.parse("x = 3; f'Hi {x}'")
Segmentation fault: 11
```
f-strings without variables inside are parsed correctly without error.

**Comment by kirbyfan64** [comment]
I remember this had happened in #22, but I don't remember what I did to fix it...

**Comment by ilevkivskyi** [comment]
OK, found it, here is the fix https://github.com/python/typed_ast/pull/32
