### ISSUE TITLE
mypy --fast-parser option broken with 1.0.0

### ISSUE THREAD

**Issue by sseg** [python/typed_ast#31]
Running in a Python 3.6.0 virtual environment, running mypy with --fast-parser option does not work with typed-ast==1.0.0:
```
$ pip freeze | grep 'mypy\|typed-ast'
mypy-lang==0.4.6
typed-ast==1.0.0

$ mypy --fast-parser .
You must install the typed_ast package before you can run mypy with `--fast-parser`.
You can do this with `python3 -m pip install typed-ast`.
```

The same run works with typed-ast==0.6.3

**Comment by ethanhs** [comment]
mypy has moved to the `mypy` package name, and is at version 0.471, if you update mypy to 0.471, does that fix the issue?

**Comment by gvanrossum** [comment]
It's expected that mypy 0.47* doesn't work with typed-ast 1.0+.

--Guido (mobile)

**Comment by ddfisher** [comment]
This is expected -- typed_ast made some backwards incompatible changes when updating to 1.0.

To fix, use **mypy** (no longer **mypy-lang**) version 0.471, which has an upper bound on the typed-ast version it installs.  The next release of mypy will be out in a couple weeks and will be updated to work with typed-ast 1.0.

**Comment by sseg** [comment]
Resolved with the **mypy** for me. Thanks all.

Leaving a link here to the blog post explaining the changes for anyone else coming across this: http://mypy-lang.blogspot.com/2017/01/mypy-0470-released.html
