### ISSUE TITLE
parsing f-strings -- opening brace gets duplicated when backslash is followed by an expression

### ISSUE THREAD

**Issue by mbdevpl** [python/typed_ast#34]
with Python 3.6.0 and typed-ast 1.0.2, I get the following:

```
#!/usr/bin/env python3.6

import typed_ast.ast3 as ast

code1 = '''"\\{x}"'''
code2 = '''f"\\{x}"'''

tree1 = ast.parse(code1, mode='eval')
print(ast.dump(tree1))
tree2 = ast.parse(code2, mode='eval')
print(ast.dump(tree2))
```

output:

```
Expression(body=Str(s='\\{x}'))
Expression(body=JoinedStr(values=[Str(s='\\{'), FormattedValue(value=Name(id='x', ctx=Load()), conversion=-1, format_spec=None)]))
```

Therefore, the normal string is `'\\{x}'`.
But the f-string has two parts: `'\\{'` and an expression `Name(id='x', ctx=Load())`.

Where does the `{` in the string part of f-string come from? This happens also with built-in ast. I can't believe this is the intended behavior... Is it?

**Comment by gvanrossum** [comment]
What does the stdlib ast module print for the same inputs?

**Comment by kirbyfan64** [comment]
> This happens also with built-in ast.

Sounds like you might have hit a CPython bug...

**Comment by mbdevpl** [comment]
The same things:

```
Expression(body=Str(s='\\{x}'))
Expression(body=JoinedStr(values=[Str(s='\\{'), FormattedValue(value=Name(id='x', ctx=Load()), conversion=-1, format_spec=None)]))
```

Also, I just noticed that when I escape the backslash once, what gets parsed is actually unescaped backslash. So this might just boil down to inconsistency in parsing `\{` in normal vs. f-strings.

**Comment by gvanrossum** [comment]
Check the PEP, there's a rule against backslashes before curly braces.

**Comment by ddfisher** [comment]
It looks like the PEP only disallows backslashes _within_ fstrings.  @mbdevpl: this seems like a CPython bug -- could you file it in [the Python bug tracker](http://bugs.python.org/)?

typed_ast's is intended to match the implicit spec that is CPython, so until this behavior is fixed upstream, typed_ast is behaving correctly.

**Comment by mbdevpl** [comment]
Sure, thanks for taking a look! I had yet another careful read of the PEP, and I also cannot find anything about backslashes being disallowed outside of expressions. The only mention of `\{` seems to be in discussion about possible alternate expression opening/closing delimiters.

I reported this issue here: https://bugs.python.org/issue29814

**Comment by gvanrossum** [comment]
Where it was deemed a dupe of https://bugs.python.org/issue29104.
