### ISSUE TITLE
The latest version 1.0.4 installation fails under Python 3.4 in Windows

### ISSUE THREAD

**Issue by webknjaz** [python/typed_ast#46]
See this Appveyor build: https://ci.appveyor.com/project/asvetlov/multidict/build/1.0.0a0.dev477/job/isj75vxav52hwf3j#L262

**Comment by ethanhs** [comment]
Do you mean a check in typed_ast or mypy? I think an error message if typed_ast is built on an unsupported platform/python version combination might be a good thing. Ultimately up to @ddfisher.

**Comment by webknjaz** [comment]
I meant error message `typed_ast`, which would look user-friendly and would have a reference to corresponding issue.

**Comment by ethanhs** [comment]
I actually just made a patch which should build typed_ast on VS2010, so it would work with Python 3.4. VS2010 makes some things more complicated so even if my patch is accepted, mypy still wouldn't support 3.4 due to lxml.

**Comment by webknjaz** [comment]
Nevermind, I've just disabled installing `mypy` in non-supported env. Anyway we don't run it in Appveyor.

**Comment by ethanhs** [comment]
Just as follow up, typed_ast (and thus mypy) work on Windows with Python 3.3 and 3.4

**Comment by webknjaz** [comment]
Thanks for the info :+1:

**Comment by webknjaz** [comment]
I should mention that it requires some conditional magic until new mypy version released (ref python/mypy#3802):
https://github.com/aio-libs/multidict/blob/dd078b2112bf15f0158cf8497c5bdafa7f25912a/requirements/ci.txt#L11-L12
