### ISSUE TITLE
Misplaced type annotations should be a warning or list

### ISSUE THREAD

**Issue by Wilfred** [python/typed_ast#59]
Given the Python code:

```python
def wrong1():
    "A docstring."
    # type: () -> int
    return 42


def wrong2():
    "A docstring."
    # type: () -> int
    return 42
```

typed_ast raises a `SyntaxError` on the first misplaced comment:

```
In [8]: ast27.parse("""def wrong1():
   ...:     "A docstring."
   ...:     # type: () -> int
   ...:     return 42
   ...:
   ...:
   ...: def wrong2():
   ...:     "A docstring."
   ...:     # type: () -> int
   ...:     return 42
   ...: """)
Traceback (most recent call last):

  File "/users/wilfred/.conda/envs/ast_scratch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-8-ebf02dacb9b0>", line 11, in <module>
    """)

  File "/users/wilfred/.conda/envs/ast_scratch/lib/python3.6/site-packages/typed_ast/ast27.py", line 51, in parse
    return _ast27.parse(source, filename, mode)

  File "<unknown>", line 3
    # type: () -> int
                    ^
SyntaxError: misplaced type annotation
```

This means that it's not possible to get a list of all the misplaced type annotations.

**Comment by ethanhs** [comment]
Generally, the ast module will stop parsing on the first syntactic error. To me it seems that it would be inconsistent to special case type comments and report all of them.

**Comment by gvanrossum** [comment]
Realistically this won't be fixed -- Python always stops at the first
syntactic error.

**Comment by JukkaL** [comment]
A partial workaround for this in the context of mypy is to make mypy run much faster, so that reporting just a single error is less of a problem.

**Comment by gvanrossum** [comment]
Another consideration: IIRC we currently bail immediately when we have a syntax error in a module. I think it would be better to at least continue parsing the remaining modules in the argument list, so at least we can report one syntax error *per file* rather than *per run*. (OTOH when a file doesn't exist at all we should probably bail before anything has been parsed.)
