### ISSUE TITLE
Issue with string length using Latin-1 encoding

### ISSUE THREAD

**Issue by Lucas-C** [python/typed_ast#65]
Hello.

I'm working on a bug affecting `pylint`, which uses `astroid`, which uses `typed_ast`:
https://github.com/PyCQA/pylint/issues/2610

What troubles me is the `.col_offset` value of a `Str` node containing a non-ASCII character with Latin1 encoding.

Here is a minimal code example:
```
# coding: latin_1
from typed_ast import ast3
print(ast3.parse("'a'+'A'").body[0].value.right.col_offset)  # print: 4
print(ast3.parse("'à'+'A'").body[0].value.right.col_offset)  # print: 5
```

From my understanding a "`é`" character as a length of 1 in Latin-1:
https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Code_page_layout

Hence, could someone help me understanding why the `.col_offset` is higher in that case, please ?

**Comment by gvanrossum** [comment]
OK, then let's close this as won't fix -- but feel free to report this in the CPython bug tracker (bugs.python.org).
