### ISSUE TITLE
Use PEP 561 style typing information instead of typeshed?

### ISSUE THREAD

**Issue by msullivan** [python/typed_ast#71]
typeshed isn't versioned at all, and we have made some API changes across versions.

**Comment by JukkaL** [comment]
Sounds like a good idea to me.

**Comment by gvanrossum** [comment]
Why is this in typed_ast?

**Comment by ethanhs** [comment]
@gvanrossum I think the idea was to move the stubs for typed_ast from https://github.com/python/typeshed/tree/master/third_party/3/typed_ast to this package.

**Comment by gvanrossum** [comment]
Oh duh, it's about the typing info for typed_ast itself. :-)

**Comment by alaalial** [comment]
@ethanhs 
what the difference between typeshed and the typed_ast , currently we can not use typed_ast ?

**Comment by JelleZijlstra** [comment]
@alaalial I don't know what that question means. You can look at the READMEs for the typeshed and typed-ast repos to see what they are about.

As for this issue, I think it's probably no longer worthwhile to merge the typed-ast stubs in this repo, as the typed-ast project is becoming obsolete. The only changes recently have tended to be compilation fixes for new Python versions.
