### ISSUE TITLE
Str.kind exists but Bytes.kind doesn't - what's the design here?

### ISSUE THREAD

**Issue by mbdevpl** [python/typed_ast#74]
I'm not sure if it's a bug, or a feature, but at least to me the following:

>     - `Str` has a `kind` string field which preserves the original string
>      prefix, so that `ast3.parse('u"test"').body[0].value.kind == 'u'`. 

from https://github.com/python/typed_ast/blob/master/typed_ast/ast3.py#L24 suggests that raw strings are also supported, and indeed they are. However, in case of raw bytes the prefix is lost. Is this by design?

Currently it's like this:

```
In [1]: import typed_ast                                                                                 

In [2]: typed_ast.__version__                                                                            
Out[2]: '1.2.0'

In [3]: from typed_ast.ast3 import parse, dump                                                           

In [4]: dump(parse('''r"spam"'''))                                                                       
Out[4]: "Module(body=[Expr(value=Str(s='spam', kind='r'))], type_ignores=[])"

In [5]: dump(parse('''rb"spam"'''))                                                                      
Out[5]: "Module(body=[Expr(value=Bytes(s=b'spam'))], type_ignores=[])"
```

Preserving the original prefix of string is useful for many reasons, same can be said about preserving the original bytes prefix, i.e. parsing `rb"spam"` into for example `Bytes(s=b'spam', kind='rb')`.

However, as I'm not sure what was the reason behind adding that `kind` field to `Str`, I'm not sure if the same reason can be applied to `Bytes` as well. And by the way, is there any place where the choice of preserving `kind` at all is explained?

**Comment by JelleZijlstra** [comment]
I think the addition of `Str.kind` was motivated by some specific need in mypy, I forgot exactly what. It would make sense to do the same for `Bytes` though.
