### ISSUE TITLE
Base version numbers on Python releases?

### ISSUE THREAD

**Issue by msullivan** [python/typed_ast#81]
Since typed_ast is a fork of `ast`s from specific python versions, I think it would make sense to make the version numbers be tied to the Python release that it was forked from, with a minor version and a patch number appended.

This would make the upcoming release be `3.7.2.0.0` (which by PEP 440 can be abbreviated as `3.7.2`).

**Comment by gvanrossum** [comment]
That's not a bad idea (though I think maybe one `.0` is enough?).

**Comment by msullivan** [comment]
Two allows us to be more like semver, bumping a patch number for bugfixes and a minor version when things might break. Not having that might be fine, though, for something like typed_ast that probably needs to be version pinned pretty carefully?

**Comment by gvanrossum** [comment]
Hm, now I'm less sure about this. I think I'd rather have 1.3.0, 1.3.1 than 3.7.2.0.0, 3.7.2.0.1. Or even 3.7.2.0, 3.7.2.1. We had to do a brown bag release for typing (which does use this versioning scheme) and it was pretty ugly.

**Comment by gvanrossum** [comment]
Let's not. We'll probably never have a new version of typed_ast based on Python 3.8 (instead, Python 3.8's ast module supports type comments, and mypy works with this).
